platform :ios, '10.0'
use_frameworks!
def common_pods
  pod 'Alamofire', '4.8.2'
  pod 'IQKeyboardManagerSwift', '6.5.0'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'NVActivityIndicatorView', '4.8.0'
end

target 'Klikdokter' do
  common_pods
end
  

target 'KlikdokterTests' do
  common_pods
end

target 'KlikdokterUITests' do
  common_pods
end
